### ISSUE TITLE
Hash not always updating in dev

### ISSUE THREAD

**Issue by mattfordham** [wycats/rack-offline#15]
Hi there,

When I reload the manifest in my browser (http://localhost:3000/application.manifest, Safari) , I would expect to see the hash change on every reload. It is not. It randomly changes ever 5-10 times or so. Every time I reload, however, Webrick shows this:

`Started GET "/application.manifest" for 127.0.0.1 at 2012-01-23 11:57:24 -0800`

I am definitely in development mode and am not caching classes. Any ideas? Thanks!

**Comment by moll** [comment]
I think either the README or the code itself points out that because of some browser download behavior the hash is randomly changed every n-seconds, and not on every reload.

It might've had something to do with a browser downloading the manifest, downloading the assets and then rechecking the manifest. And if the manifest changed every request, it'd end up in a loop.

**Comment by wycats** [comment]
Unfortunately, Chrome forces us to use a timer here instead of "change it on every reload". :(
